changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
   - title: 📺 Video Player
      labels:
        - Video Player
        - player
    - title: 🚀 Features
      labels:
        - feature
        - feat
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
        - bugfix
    - title: 🚀 Breaking Changes
      labels:
        - breaking-change
    - title: Other Changes
      labels:
        - "*" # Catch-all for pull requests that didn't match any of the previous 
