# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:
  push:
    tags: 
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: |
        yarn install
        echo VERSION=$(node -e "console.log(require('/package.json').version);") >> $GITHUB_ENV
        echo 'Build v' ${{ env.VERSION }}
    - uses: EndBug/add-and-commit@v9
      with:
        add: 'package.json README.md'
        default_author: github_actions
        message: 'Build v${{ env.VERSION }}'
          
