name: Release New Player Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to be released (must follow semantic versioning)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./anne_lima_app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate version
        id: validate_version
        run: |
          VERSION=${{ github.event.inputs.version }}
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version number must follow semantic versioning (MAJOR.MINOR.PATCH)"
            exit 1
          fi
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Error: Tag v$VERSION already exists"
            exit 1
          fi
          echo "::set-output name=version::$VERSION"

      - name: Update package.json
        run: |
          VERSION=${{ steps.validate_version.outputs.version }}
          jq --arg version "$VERSION" '.version = $version' package.json > tmp.$$.json && mv tmp.$$.json package.json
          npm install
          git config --global user.email "exageradonome@gmail.com"
          git config --global user.name "josewd"
          git checkout -b release/v$VERSION
          git commit -am "Bump version to v$VERSION"
          git push origin release/v$VERSION

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Bump version to v${{ steps.validate_version.outputs.version }}
          branch: release/v${{ steps.validate_version.outputs.version }}
          base: master # ou develop, dependendo do seu branch de destino
          title: 'Release v${{ steps.validate_version.outputs.version }}'
          body: 'Automated release of version v${{ steps.validate_version.outputs.version }}'

      - name: Wait for PR to be merged
        id: wait_for_merge
        uses: actions/github-script@v3
        with:
          script: |
            const prs = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `release/v${{ steps.validate_version.outputs.version }}`,
            });
      
            if (prs.data.length === 0) {
              throw new Error(`Pull request for branch release/v${{ steps.validate_version.outputs.version }} not found`);
            }
      
            const prNumber = prs.data[0]?.number;
      
            let isMerged = false;
            while (!isMerged) {
              const { data: pr } = await github.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
              });
      
              if (pr.merged) {
                isMerged = true;
              } else {
                console.log(`PR #${prNumber} not merged yet. Waiting...`);
                await new Promise(resolve => setTimeout(resolve, 60000)); // Espera 1 minuto antes de verificar novamente
              }
            }
      
            return { prNumber };
      - name: Merge Pull Request
        uses: actions/github-script@v4
        with:
          script: |
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ steps.wait_pr.outputs.prNumber }},
              merge_method: 'squash'
            });

      - name: Create Tag
        run: |
          VERSION=${{ steps.validate_version.outputs.version }}
          git fetch --tags
          git tag v$VERSION
          git push origin v$VERSION

      - name: Generate Release Notes
        id: generate_release_notes
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: .github/release-changelog-config.json
          tag: v${{ steps.validate_version.outputs.version }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.validate_version.outputs.version }}
          release_name: v${{ steps.validate_version.outputs.version }}
          body: ${{ steps.generate_release_notes.outputs.changelog }}
          draft: false
          prerelease: false
