# This is a basic workflow that is manually triggered

name: Build and Deploy to S3 by version

on:
  push:
    tags: 
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./anne_lima_app
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: |
        npm install
        echo VERSION=$(node -e "console.log(require('./package.json').version);") >> $GITHUB_ENV
        
    - name: 'Deploy v${{ env.VERSION }}'
      run: |
        echo 'Deploy v${{ env.VERSION }}'
         
          
